### ISSUE TITLE
Dockerize Dev Env

### ISSUE THREAD

**Issue by StefanSchade** [StefanSchade/docu-flow#2]
### Dockerize Development Environment

as a developer, I want to have a docker environment I can work on|

### Tasks

- [ ] Create development Dockerfile
- [ ] Add necessary dependencies for the project
- [ ] Create a build script
