### ISSUE TITLE
Create Docker Production Setup

### ISSUE THREAD

**Issue by StefanSchade** [StefanSchade/docu-flow#3]
### Requirement

For the production setup, I want to have a suitable Dockerized deployment

### Tasks

- [ ] Create Dockerfile.prod
- [ ] Configure Dockerfile with prod dependencies
- [ ] Provide necessary scripts
