### ISSUE TITLE
Configure CI/CD Pipeline

### ISSUE THREAD

**Issue by StefanSchade** [StefanSchade/docu-flow#4]
### Requirements

I want to have a continuous integration pipe with Github Actions or another CI tool\
I want to include steps for building and testing

### Tasks

- [ ] Create .github/workflows
- [ ] Add CI Workflow for Build
- [ ] Add Steps to run basic tests
